/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_joice_ndkproject_MyNdk */

#ifndef _Included_com_android_joice_ndkproject_MyNdk
#define _Included_com_android_joice_ndkproject_MyNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_joice_ndkproject_MyNdk
 * Method:    getMyString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_joice_ndkproject_MyNdk_getMyString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
