/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_joice_ndkproject_nativecode_StoreThreadSafe */

#ifndef _Included_com_android_joice_ndkproject_nativecode_StoreThreadSafe
#define _Included_com_android_joice_ndkproject_nativecode_StoreThreadSafe
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
